# Generated by Django 3.0.4 on 2020-04-08 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200407_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
